---
title: "ADA_estimation"
author: "Jessica Guo"
date: "2023-07-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(1000)
library(topicmodels)
library(dplyr)
library(NLP)
library(papeR)
library(tidytext)
library(ggplot2)
library(tm)
library(tidyr)
library(wordcloud)
library(rJava)
library(randChecks)
library(stm)
library(quanteda)
library(quanteda.sentiment)
library(quanteda.dictionaries)
library(quanteda.corpora)
library(quanteda.textstats)
library(textreg)
library(MatchIt)
library(data.table)
library(cobalt)
library(designmatch)
library(cem)
library(lsa)
library(SuperLearner)
library(npcausal)
library(lmtest)
library(sandwich)
library(sensitivitymw)
```


```{r, doubly robust}
# log(Y+1) scale
ate_full_ups <-ate(log(cov_15$ups+1),cov_15$gender,cov_15[,!names(cov_15) %in% c("gender","num_comments")],
                      nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))

ate_full_comm <-ate(log(cov_15$num_comments+1),cov_15$gender,cov_15[,!names(cov_15) %in% c("gender","ups")],
                      nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))

# original scale
ate_full_ups_og <-ate(cov_15$ups,cov_15$gender,cov_15[,!names(cov_15) %in% c("gender","num_comments")],
                      nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))

ate_full_comm_og <-ate(cov_15$num_comments,cov_15$gender,cov_15[,!names(cov_15) %in% c("gender","ups")],
                      nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))

ps_npcausal <- ate_full_ups_og$nuis$pi_a1[cardmatch$weights == "1"]
saveRDS(ps_npcausal, file = "ps_npcausal.RDS")
# after matching, log(Y+1)
cov_names <- names(subset(cov_15,select = -c(gender,ups,num_comments)))
ate_m_ups <- ate(log(matched.cardglm$ups+1), matched.cardglm$gender,
                 matched.cardglm[,names(matched.cardglm) %in% cov_names],
                 nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))
ate_m_comm <- ate(log(matched.cardglm$num_comments+1), matched.cardglm$gender,
                  matched.cardglm[,names(matched.cardglm) %in% cov_names],
                 nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))

# original scale
ate_m_ups_og <- ate(matched.cardglm$ups, matched.cardglm$gender,
                 matched.cardglm[,names(matched.cardglm) %in% cov_names],
                 nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))
ate_m_comm_og <- ate(matched.cardglm$num_comments, matched.cardglm$gender,
                  matched.cardglm[,names(matched.cardglm) %in% cov_names],
                 nsplits = 2, sl.lib = c("SL.glm","SL.ranger","SL.glmnet","SL.gam"))
```


```{r, mean diff}
full_comm_tau <- mean(log(cov_15$num_comments[cov_15$gender == "1"]+1))-
  mean(log(cov_15$num_comments[cov_15$gender == "0"]+1))
se_full_comm <- 1.96*sqrt(var(log(cov_15$num_comments[cov_15$gender == "1"]+1))/nrow(cov_15[cov_15$gender == "1",])+var(log(cov_15$num_comments[cov_15$gender == "0"]+1))/nrow(cov_15[cov_15$gender == "0",]))


full_ups_tau <- mean(log(cov_15$ups[cov_15$gender == "1"]+1))-
  mean(log(cov_15$ups[cov_15$gender == "0"]+1))
se_full_ups <- 1.96*sqrt(var(log(cov_15$ups[cov_15$gender == "1"]+1))/nrow(cov_15[cov_15$gender == "1",])+var(log(cov_15$ups[cov_15$gender == "0"]+1))/nrow(cov_15[cov_15$gender == "0",]))

m_comm_tau <- mean(log(matched.cardglm$num_comments[matched.cardglm$gender == "2"]+1))-
  mean(log(matched.cardglm$num_comments[matched.cardglm$gender == "1"]+1))
se_m_comm <- 1.96*sqrt(var(log(matched.cardglm$num_comments[matched.cardglm$gender == "2"]+1))/nrow(matched.cardglm[matched.cardglm$gender == "2",])+var(log(matched.cardglm$num_comments[matched.cardglm$gender == "1"]+1))/nrow(matched.cardglm[matched.cardglm$gender == "1",]))

m_ups_tau <- mean(log(matched.cardglm$ups[matched.cardglm$gender == "2"]+1))-
  mean(log(matched.cardglm$ups[matched.cardglm$gender == "1"]+1))
se_m_ups <- 1.96*sqrt(var(log(matched.cardglm$ups[matched.cardglm$gender == "2"]+1))/nrow(matched.cardglm[matched.cardglm$gender == "2",])+var(log(matched.cardglm$ups[matched.cardglm$gender == "1"]+1))/nrow(matched.cardglm[matched.cardglm$gender == "1",]))
```



```{r, linear reg plug in}
# full
cov_15 = cov_15%>%  mutate_at(c("gender","Jan_indic","Feb_indic","Mar_indic","Apr_indic",
                                "May_indic","Jun_indic","Jul_indic","Aug_indic",
                                "Sep_indic","Oct_indic","Nov_indic","Dec_indic"), as.numeric(as.character()))
x2 <- matrix(nrow = nrow(cov_15), ncol = 71)
for (i in 1:71){
  x2[,i] = scale(cov_15[,-c(46,73,74)][,i],scale = F)
}
x3 <- cov_15$gender*x2
colnames(x3) <- paste(colnames(cov_15[,-c(46,73,74)]), "gender", sep=":")
data_full = cbind(cov_15,x3)
lm_lasso_ups <- lm(ups~.-num_comments, data = data_full)
coefci(lm_lasso_ups, vcov = vcovHC(lm_lasso_ups, type = "HC2"))

lm_lasso_comm <- lm(num_comments~.-ups, data = data_full)
coefci(lm_lasso_comm, vcov = vcovHC(lm_lasso_comm, type = "HC2"))

# matched
matched.cardglm = matched.cardglm %>%  mutate_at(c("gender","Jan_indic","Feb_indic",
                                                       "Mar_indic","Apr_indic",
                                "May_indic","Jun_indic","Jul_indic","Aug_indic",
                                "Sep_indic","Oct_indic","Nov_indic","Dec_indic"), as.numeric)
x2 <- matrix(nrow = nrow(matched.cardglm), ncol = 71)
for (i in 1:71){
  x2[,i] = scale(matched.cardglm[,-c(46,73:77)][,i],scale = F)
}
x3 <- matched.cardglm$gender*x2
colnames(x3) <- paste(colnames(matched.cardglm[,-c(46,73:77)]), "gender", sep=":")
data_full = cbind(matched.cardglm[, !names(matched.cardglm) %in% c("distance","weights","subclass")] ,x3)
lm_lasso_ups <- lm(ups~.-num_comments, data = data_full)
coefci(lm_lasso_ups, vcov = vcovHC(lm_lasso_ups, type = "HC2"))

lm_lasso_comm <- lm(num_comments~.-ups, data = data_full)
coefci(lm_lasso_comm, vcov = vcovHC(lm_lasso_comm, type = "HC2"))

```


```{r, plots}
# Propensity Score by gender

# full
findex_full = which(cov_15$gender == "1")
plot(density(ate_full_ups$nuis$pi_a1[findex_full]),col = "red",main = "PS Plot, Full",xlab = "")
lines(density(ate_full_ups$nuis$pi_a1[-c(findex_full)]),col = "blue")
legend('topleft',legend=c("Female", "Male"),
       col=c("red", "blue"), lty=1, cex=0.8)

# matched
findex_m = which(matched.cardglm$gender == "1")
plot(density(ate_m_ups$nuis$pi_a1[findex_m]),col = "red",main = "PS Plot, Matched")
lines(density(ate_m_ups$nuis$pi_a1[-c(findex_m)]),col = "blue")
legend('topleft',legend=c("Female", "Male"),
       col=c("red", "blue"), lty=1, cex=0.8)
```


```{r}
#Superlearner
# pls see sl_pred.R
# with  SL.library = c("SL.mean", "SL.glmnet", "SL.ranger","SL.knn","SL.bayesglm","SL.xgboost")
df_temp <- readRDS("df_temp.RDS")
findex <- which(df_temp$gender == "1")
plot(density(df_temp$V1[findex]),col = "red",main = "PS Plot, Full",xlab = "", xlim = c(0,1))
lines(density(df_temp$V1[-c(findex)]),col = "blue")
legend('topleft',legend=c("Female", "Male"),
       col=c("red", "blue"), lty=1, cex=0.8)

# with SL.library = c("SL.glm","SL.ranger","SL.glmnet","SL.gam")
df_temp <- readRDS("df_temp.RDS")
plot(density(df_temp$V1[findex]),col = "red",main = "PS Plot, Full",xlab = "",xlim = c(0,0.001))
lines(density(df_temp$V1[-c(findex)]),col = "blue")
legend('top',legend=c("Female", "Male"),
       col=c("red", "blue"), lty=1, cex=0.8)
# IF value differences between full and matched set
hist(ate_full_ups$ifvals[,2]-ate_full_ups$ifvals[,1],col = rgb(red = 1, green = 0, blue = 0, alpha = 0.5),
     main = "Histogram of estimated IF values differences",
     xlab = "Influence function value differences")
hist(ate_m_ups$ifvals[,2]-ate_m_ups$ifvals[,1], add = T, col = rgb(red = 0, green = 0, blue = 1, alpha = 0.5))
legend(x = "topleft",legend = c("DR - full", "DR - card+lasso matched"),
       lty = c(1, 1),
       col = c("red", "blue"),
       lwd = 2)

```

```{r sensitivy analysis}
# post matching mean diff est, sensitivity analysis using senmw()
meandiff_y_up = as.data.frame(matrix(nrow = nrow(cardnp_match_table), ncol = 2))
colnames(meandiff_y_up) <- c("female", "male")
# Extract indices
indices_1 <- cardnp_match_table[, 1]
indices_2 <- cardnp_match_table[, 2]

# Use matrix indexing to extract values
meandiff_y_up[, 1] <- data_full[indices_1, "ups"]
meandiff_y_up$female = log(meandiff_y_up$female+1)
meandiff_y_up[, 2] <- data_full[indices_2, "ups"]
meandiff_y_up$male = log(meandiff_y_up$male+1)
# sensitivity analysis
gamma_values <- seq(1, 2, by = 0.01)
p_values <- sapply(gamma_values, function(gamma) {
  senmw(meandiff_y_up, method = "t", gamma = gamma)$pval
})

plot(gamma_values, p_values, type = "l", col = "blue", xlab = "Gamma", ylab = "P-value", main = "P-value vs Gamma")
senmw(meandiff_y_up, method = "t", gamma = 1.08)

# same but for number of comments
meandiff_y_comm = as.data.frame(matrix(nrow = nrow(cardnp_match_table), ncol = 2))
colnames(meandiff_y_comm) <- c("female", "male")
meandiff_y_comm[, 1] <- data_full[indices_1, "num_comments"]
meandiff_y_comm$female = log(meandiff_y_comm$female+1)
meandiff_y_comm[, 2] <- data_full[indices_2, "num_comments"]
meandiff_y_comm$male = log(meandiff_y_comm$male+1)
senmw(meandiff_y_comm, method = "t", gamma = 1)
```



